### ISSUE TITLE
Not able to get URLEncoding working correctly when there is "?" and the method is "POST"

### ISSUE THREAD

**Issue by iballan** [Moya/Moya#1030]
I am using the last version of Moya and Alamofire with Swift 3

I am having trouble when the method is "POST" and there is url encoding 

The url must be: 
`products?id_category=28`

but it is converted to be:
`products%3Fid_category=28`

which is not working and giving 400 error on the server

where can I find this conversion and stop it for the requests ?

Here is the code i used:

```Swift
enum MyService {
	case products(categorytId: Int)
}

extension MyService : TargetType {
    
    var base: String { return Constants.MyServiceURL }
    var baseURL: URL { return URL(string: base)! }
    
    public var task: Task {
        return .request
    }

    var path : String {
        switch self {
        // i tried with and without them, changing the parameters down below
        case .products(let id_category): 
            return "products?id_category=\(id_category)"
        }
    }

    var parameterEncoding: ParameterEncoding {
	    switch self {
	        case .products:
	        	//return MyURLEncoding.queryString
	            return URLEncoding.queryString
	        default:
	            return JSONEncoding.default 
	    }
    }

    var parameters : [String : Any]? {
        switch self {
        // here I tried to add them for Testing purpose, i tried with and without them
        case .products(let id_category):
            var params: [String: Any] = [:]
            params["id_category"] = id_category
            return params
        default:
            return nil
        }
    }

    // The method must be always post always
    var method : Moya.Method {
        return .post;
    }

    var sampleDate : Data {
            return Data()
        }
    }
 }
```

**Comment by pedrovereza** [comment]
Hey @iballan could you provide more details on how you're encoding the parameters in the URL? Are you trying to send parameters in the URL and in the request body as well?

It'd be great if you could share some code that illustrates the issue :wink:

**Comment by iballan** [comment]
@pedrovereza i have updated the comment above

**Comment by pedrovereza** [comment]
@iballan Can you change your implementation of `path` to be:

```swift
 var path : String {
        switch self {
        case .products(let id_category): 
            return "products"
        }
    }
```

and `parameterEncoding` to:

```swift
var parameterEncoding: ParameterEncoding {
	    switch self {
	        case .products:
	            return URLEncoding.default
	        default:
	            return JSONEncoding.default 
	    }
    }
```

These changes will leave your code similar to the example we have in the [docs](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md) on how to send parameters in the URL when doing a POST request (see `.updateUser`)

**Comment by iballan** [comment]
@pedrovereza I have tried exactly what in the example you have mentioned, The parameters are not added at all to the request.

```
["Moya_Logger: [28/03/2017 19:47:25] Request: http://myservice/products", "Moya_Logger: [28/03/2017 19:47:25]]
Request Headers: [ \"Content-Type\": \"application/x-www-form-urlencoded; charset=utf-8\"]"
"Moya_Logger: [28/03/2017 19:47:25] HTTP Request Method: POST"]
["Moya_Logger: [28/03/2017 19:47:25] Response: <NSHTTPURLResponse: 0x7a82a150> { URL: http://myservice/products } 
{ status code: 404, headers {\n    \"Cache-Control\" = \"no-cache\";\n    \"Content-Length\" = 216;\n    \"Content-Type\" = \"application/json; charset=utf-8\";\n    Date = \"Tue, 28 Mar 2017 16:47:18 GMT\";\n    Expires = \"-1\";\n    Pragma = \"no-cache\";\n    Server = \"Microsoft-IIS/8.5\";\n    \"X-AspNet-Version\" = \"4.0.30319\";\n    \"X-Powered-By\" = \"ASP.NET\";\n} }"]
Status Code: 404, Data Length: 216
```

**Comment by avicks** [comment]
@iballan try this, I recently had the same issues and solved them by using the following (I forget where, but there was another issue raised in Moya where I cobbled together this answer, wish I could give that author credit):

```
var parameterEncoding : Moya.ParameterEncoding {
      
      switch self {
      case .feedback:
         return TokenURLEncoding.default
      default:
         return URLEncoding.default
      }
}

/// Used to append the Token to requests which require it.
/// Don't attempt to do this in the path variable, as our server can't handle % encoding..
struct TokenURLEncoding: Moya.ParameterEncoding {
   
   public static var `default`: TokenURLEncoding { return TokenURLEncoding() }
   
   
   /// Creates a URL request by encoding parameters and applying them onto an existing request.
   ///
   /// - parameter urlRequest: The request to have parameters applied.
   /// - parameter parameters: The parameters to apply.
   ///
   /// - throws: An `AFError.parameterEncodingFailed` error if encoding fails.
   ///
   /// - returns: The encoded request.
   public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
      
      var req = try urlRequest.asURLRequest()
      
      // first coerce a mutable URL out of the urlRequest
      // next, get the components of the request
      // finally, get our token
      guard let request = (req as NSURLRequest).mutableCopy() as? NSMutableURLRequest,
            let components = NSURLComponents(string: request.url!.absoluteString),
            let token = LinesSession().token else {

         // Handle the error
         return req
      }
      
      let json = try JSONSerialization.data(withJSONObject: parameters!,
                                            options: JSONSerialization.WritingOptions.prettyPrinted)

      let tokenQueryItem = NSURLQueryItem(name: "token", value: token)
      components.queryItems = [tokenQueryItem as URLQueryItem]
      
      req.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
      req.url = components.url
      req.httpBody = json

      return req
   }
}

**Comment by iballan** [comment]
@avicks the query is not added at all still to the url. I think it has something to do with the method type "Post". btw, i put debug point inside the function you have written and used it. the break point is never reached

**Comment by avicks** [comment]
@iballan The query isn't added?  

I'm using that encoding I posted to append my query item to the URL, making a POST request, and getting success.  

Would you mind elaborating on the structure behind your call?

**Comment by iballan** [comment]
@avicks 

the problem is instead of getting this as 
`URL: "http://myWebSErvice/products?id_category=30"`

I get this:  %3F
`URL: "http://myWebSErvice/products%3Fid_category=30"`

and when the "**?**" becomes "**%3F**" , the webservice throws error this  "`A potentially dangerous Request.Path value was detected from the client (?).`"

What i want is only to send the request with ? not with %3F

**Comment by pedrovereza** [comment]
Hey @iballan, we recently noticed that the documentation I pointed you to was wrong (we fixed in #1120). 😅 

Could you try using `URLEncoding.queryString` instead of `default`?

**Comment by iballan** [comment]
@pedrovereza Thank you so much for your help.

However, It is still not working :( 
You may check my Question, i already used `URLEncoding.queryString`

I tried 2 ways:
**First:** setting the query manually:
```
   var path : String {
        switch self {
        case .products(let id_category): 
            return "products?id_category=\(id_category)"
        }
    }
```
_Fail_: because **?** was encoded into **%3F**. which caused webservice 400 error.

**Second:** As you mentioned `URLEncoding.queryString`
```
   var path : String {
        switch self {
        case .products: 
            return "products"
        }
    }
    var parameterEncoding: ParameterEncoding {
	    switch self {
	        case .products:
	        	//return MyURLEncoding.queryString
	            return URLEncoding.queryString
	        default:
	            return JSONEncoding.default 
	    }
    }

   var parameters : [String : Any]? {
        switch self {
        // here I tried to add them for Testing purpose, i tried with and without them
        case .products(let id_category):
            var params: [String: Any] = [:]
            params["id_category"] = id_category
            return params
        default:
            return nil
        }
    }
```

_Fail_: Not adding the parameter at all.


What made me think that it is **Moya**'s issue, when I use **Alamofire** as I mentioned above the URL is encoded correctly and did not change **?** to **%3F**.

Now in my code I used both Moya (because i already started with it and it is a really overhead work to roll back from it) and Alamofire (to get the POST requests' url query working correctly) 👎

**Comment by pedrovereza** [comment]
I have set up an [example on how to send parameters in the URL using POST](https://github.com/pedrovereza/MoyaCarthage/blob/master/MoyaCarthage/ViewController.swift). Can you try this one out and make sure it works for you? 🤔

**Comment by chivalrousbob** [comment]
Hi everybody, today is my first time to use Moya "it is really great library", in fact I got the same problem when i use path with  this received character "?" I decided to update in the Moya even is not recommended and I'm happy to share my solution with you.
the only thing I've done is to update inside this file MoyaProvider+Defaults.swift.

update this function : 

```
 private final class func url(for target: Target) -> URL {
        if target.path.isEmpty {
            return target.baseURL
        }

        return target.baseURL.appendingPathComponent(target.path)
    }
```
with this 👍 

```
 private final class func url(for target: Target) -> URL {
        if target.path.isEmpty {
            return target.baseURL
        }
        
        let urlComponents = NSURLComponents(url: target.baseURL, resolvingAgainstBaseURL: true)!
        let index = target.path.characters.index(of: "?")
        if let index = index {
            let path = target.path.substring(to: target.path.characters.index(before: index))
            let query = target.path.substring(from: target.path.characters.index(after: index))
            urlComponents.path = path
            urlComponents.query = query
        }
        
        return urlComponents.url!
    }
```
 I hope it will help :)

**Comment by jx2359** [comment]
I've tried the above modification but it doesn't work with my other url paths without "?". So with a slight modification this works for me now

```
private final class func url(for target: Target) -> URL {
        if target.path.isEmpty {
            return target.baseURL
        }

        let urlComponents = NSURLComponents(url: target.baseURL, resolvingAgainstBaseURL: true)!
        let index = target.path.characters.index(of: "?")
        if let index = index {
            let path = target.path.substring(to: index)
            let query = target.path.substring(from: target.path.characters.index(after: index))
            urlComponents.path = path
            urlComponents.query = query
            
            return urlComponents.url!
        } else {
            return target.baseURL.appendingPathComponent(target.path)
        }
    }
```

**Comment by chivalrousbob** [comment]
hi @jx2359 I updated my code you can check agin it will work with the other url also

**Comment by jx2359** [comment]
hi @chivalrousbob, I tried your code again but I got an exception at the last line when the url has no parameters in the path. 

I forgot to add that in my previous comment I've also modified the line where "path" is generated. `target.path.substring(to: target.path.characters.index(before: index))` returns the path with the last character removed, and it results in a 404 response.

**Comment by bawn** [comment]
I have same issues.

**Comment by WeiRujian** [comment]
enum MoyaApi {
    case Login(username: String, password: String)

}

extension MoyaApi: TargetType {
    /// The method used for parameter encoding.
  
    
    var baseURL: URL {
        return URL(string:"http://192.168.1.108:86")!
    }
    
    var path: String {
        switch self {
        case .Login(_,_):
            return "/api/xlogin.ashx?action=xulogin"
        }
    }
    
    var method: Moya.Method {
        switch self {
        case .Login(_,_):
            return .post
        }
    }
    
    var parameters: [String: Any]? {
        switch self {
        case .Login(username: let name, password: let pwd):
            return ["xuname": name, "xupwd": pwd]
        }
    }
    
    var parameterEncoding: ParameterEncoding {
        return URLEncoding.default
    }
    
    var sampleData: Data {
        switch self {
        case .Login(_,_):
            return "Create post successfully".data(using: String.Encoding.utf8)!
        }
    }
    
    var task: Task {
        return .request

    }
    
    var validate: Bool {
        return false
    }

Requested URL：http://192.168.1.108:86/api/xlogin.ashx?action=xulogin 
method：post
Param：Optional(["xuname": "13977823556", "xupwd": "123456"]) 
Status Code: 404, Data Length: 1163

Why return 404？

**Comment by AnupamKatiyar** [comment]
@iballan  You have to write custom endpoints like this:

print("baseURL:\(target.baseURL)\n path:\(target.path)")


let url = target.baseURL.absoluteString + target.path

print("url:\(url)")
//http://XXXX/api/xlogin.ashx?action=xulogin


//This method will escape special characters
//let url = target.baseURL.appendingPathComponent(target.path).absoluteString
//http://XXXX/api/xlogin.ashx%3Faction=xulogin


let endpoint = Endpoint<RequestAPI>(
    url: url,
    sampleResponseClosure: { .networkResponse(200, target.sampleData) },
    method: target.method,
    parameters: target.parameters,
    parameterEncoding: target.parameterEncoding
)

//Set up your header information
return endpoint.adding(newHTTPHeaderFields: [:])

**Comment by dmitrykurochka** [comment]
@iballan Did you find any solutions? Have the same problem

**Comment by iballan** [comment]
@dmitrykurochka  I use Alamofire directly for functions that has & in Post methods's url

**Comment by dmitrykurochka** [comment]
@iballan Looks like I have found solution. You should use own Endpoint and url stay correct without changing from '?' to '%3F'
 This my real method that works for this situation
    let authPlugin = AccessTokenPlugin(token: token)
    let provider = RxMoyaProvider<Service>(endpointClosure: {target in
      return Endpoint(
        url: "\(target.baseURL)\(target.path)",
        sampleResponseClosure: { .networkResponse(200, target.sampleData) },
        method: target.method,
        parameters: target.parameters,
        parameterEncoding: target.parameterEncoding
      )
    }, plugins: [authPlugin])

**Comment by iballan** [comment]
Yes, I guess the whole problem was because I used the same function, without the last parameter:

`parameterEncoding: target.parameterEncoding`

by adding it to the endpoint constructor now it works

**Comment by noizar** [comment]
try use this
```
var baseURL: URL{
        switch self {
        case .chagePassword(_,_,let token):
             return URL(string: "base_url?token=\(token)")!
        default:
            return URL(string: "base_url")!
        }
    }

var path:String{
        switch self {
        case .chagePassword:
            return "/api/update-password"
        }
    }
```
and  url request  will like this "base_url/api/update-password?token="114149814189"

**Comment by mayuur** [comment]
@noizar your solution works! but how? I am curious.

**Comment by SD10** [comment]
@mayuur It works because "?" should not be part of the path. It indicates the query. Therefore, the `appendingPathComponent` method will encode the "?" as "%3F".

**Comment by williampenna** [comment]
For me it didn't get yet.
The difference is that I'm using .get

But the problem still happens, it converts the "?" to "%3F"

**Comment by WangShunYang** [comment]
@iballan  i have same problem ,can you send me a example how to save this problem? thx

**Comment by WangShunYang** [comment]
@noizar  it works for me

**Comment by AhmAbdallah** [comment]
I want to call this  https://www.blaalb.com/restApi/testApi/myOrders?number=1&month=24

```
enum MyWebService {
    switch self {
       case getMyOrders(number: Int, month: Int)
   }
}

var path: String {
   switch self {
      case . getMyOrders:
      return "/myOrders"
     }
  }
}

var method: Moya.Method {
     switch self {
      case .getMyOrders:
      return .get
   }
}

var task: Task {
    switch self {
      case . getMyOrders(let number, let month):
      let p = ["number" : number,
               "month": month]
    return .requestParameters(parameters:p , encoding: URLEncoding.default)
 }
}
```

**Comment by WeiRuJian** [comment]
> 我想称这个为 https://www.blaalb.com/restApi/testApi/myOrders?number=1&month=24
> 
> ```
> enum MyWebService {
>     switch self {
>        case getMyOrders(number: Int, month: Int)
>    }
> }
> 
> var path: String {
>    switch self {
>       case . getMyOrders:
>       return "/myOrders"
>      }
>   }
> }
> 
> var method: Moya.Method {
>      switch self {
>       case .getMyOrders:
>       return .get
>    }
> }
> 
> var task: Task {
>     switch self {
>       case . getMyOrders(let number, let month):
>       let p = ["number" : number,
>                "month": month]
>     return .requestParameters(parameters:p , encoding: URLEncoding.default)
>  }
> }
> ```

你需要自定义EndpointClosure
```
private let myEndpointClosure = { (target: MultiTarget) -> Endpoint in
    let url = target.baseURL.absoluteString + target.path

    let endpoint = Endpoint(url: url,
                            sampleResponseClosure: { .networkResponse(200, target.sampleData) },
                            method: target.method,
                            task: target.task,
                            httpHeaderFields: target.headers)
    return endpoint
}
```

**Comment by winterwd** [comment]
> try use this
> 
> ```swift
> var baseURL: URL{
>         switch self {
>         case .chagePassword(_,_,let token):
>              return URL(string: "base_url?token=\(token)")!
>         default:
>             return URL(string: "base_url")!
>         }
>     }
> 
> var path:String{
>         switch self {
>         case .chagePassword:
>             return "/api/update-password"
>         }
>     }
> ```
> 
> and url request will like this "base_url/api/update-password?token="114149814189"

tks u for this 👍

**Comment by hassan31** [comment]
Hi everyone, if your full URL is like this:
`https://www.yourdomain.com/api/home_gp/api_180913.php?request=login`

then you have to use the following solution, it works for me.

your base URL will be this `https://www.yourdomain.com/api/home_gp/api_180913.php` and you have to pass the request endpoint as a parameter like below:

<img width="767" alt="Screen Shot 2020-06-19 at 8 37 57 PM" src="https://user-images.githubusercontent.com/3063382/85187649-f84a7f80-b26e-11ea-9103-65763f328bf6.png">

**Comment by Oytunkdnz** [comment]
Is there anyone who can help in my situation?


enum AuctionType {
    case ongoing,completed
}


enum MyDomainAPI {
    case login(email: String ,password: String,deviceKey :String)
    case auctionOngoing(startIndex:Int,endIndex:Int)
    case auctionCompleted(startIndex:Int,endIndex:Int)
    case auctionsForCompany(startIndex:Int,endIndex:Int)
    case auction(auctionid: Int)
    case ipAdress
    case auctionsFilter
    case auctionFollow(auctionid:Int)
    case auctionUnFollow(auctionid:Int)
    case auctionFollowList
    case onGoingAuctionVehicleListByCompany(companyID:Int,cityID:Int,endDate:String,startIndex:Int,endIndex:Int)
    case setBidAuctionVechileList(startIndex:Int,endIndex:Int)
    case saleComplateAuctionVehicleList(startIndex:Int,endIndex:Int)
    case search(request: FMSearchRequest)
    case notifications
    case auctionVisit(auctionID:String)
    case resetPassword(email:String)
    
}

extension MyDomainAPI: TargetType {

    
    public var baseURL: URL {
        return URL(string: "https://api.MyDomain.com.tr/AuctionService.svc/")!
        
        
        
        
    }
    
    public var path: String {
        
        switch self {
            
        case .login:
            return "ServiceLogin"
            
        case .auctionOngoing:
            return "GetOnGoingAuctionVehicleList"
            
        case .auctionCompleted:
            return "GetCompletedAuctionVehicleList"
            
        case .auctionsForCompany:
            return "GetOngoingAuctionVehicleCountList"
            
        case .auction:
            return "GetVehicleDetails"
            
        case .auctionFollow:
            return "AuctionFollow"
            
        case .auctionUnFollow:
            return "AuctionUnFollow"
            
        case .auctionsFilter:
            return "GetOnGoingAuctionDataLists"
            
        case .ipAdress:
            return "GetIPAddress"
            
        case .auctionFollowList:
            return "GetAuctionFollowList"
            
        case .onGoingAuctionVehicleListByCompany:
            return "GetOnGoingAuctionVehicleListByCompany"
            
        case .setBidAuctionVechileList:
            return "GetSetBidAuctionVehicleList"
            
        case .saleComplateAuctionVehicleList:
            return "GetSaleComplateAuctionVehicleList"
            
        case .search:
            return "Search"
            
        case .notifications:
            return "GetUserNotifications"
            
        case .auctionVisit:
            return "AuctionVisit"

        case .resetPassword:
            return "ResetPassword"
        }
    }
    
    public var method: Moya.Method {
        
        switch self {
        case .ipAdress, .auctionFollowList, .auctionsFilter:
            return .get
            
        default:
            return .post
        }
    }
    
    public var sampleData: Data {
        return Data()
    }
    
    public var task: Task {
        
        switch self {
            
        case .login(let email, let password,let deviceKey):
            return .requestParameters(parameters: ["email":email, "password":password, "devicekey":deviceKey], encoding: JSONEncoding.default)
            
        case .auctionOngoing(let startIndex ,let endIndex):
            return .requestParameters(parameters: ["startindex":startIndex, "endindex":endIndex], encoding: JSONEncoding.default)
            
        case .auctionCompleted(let startIndex ,let endIndex):
            return .requestParameters(parameters: ["startindex":startIndex, "endindex":endIndex], encoding: JSONEncoding.default)
            
        case .auctionsForCompany(let startIndex ,let endIndex):
            return .requestParameters(parameters: ["startindex":startIndex, "endindex":endIndex], encoding: JSONEncoding.default)
            
        case .auction(let auctionid):
            return .requestParameters(parameters: ["auctionid":auctionid], encoding: JSONEncoding.default)
            
        case .auctionFollow(let auctionid):
            return .requestParameters(parameters: ["auctionid":auctionid], encoding: JSONEncoding.default)
            
        case .auctionUnFollow(let auctionid):
            return .requestParameters(parameters: ["auctionid":auctionid], encoding: JSONEncoding.default)
            
        case .onGoingAuctionVehicleListByCompany(let companyID,let cityID,let endDate,let startIndex,let endIndex):
            return .requestParameters(parameters: ["companyid":companyID,"cityid":cityID,"enddate":endDate,"startindex":startIndex,"endindex":endIndex], encoding: JSONEncoding.default)
            
        case .setBidAuctionVechileList(let startIndex ,let endIndex):
            return .requestParameters(parameters: ["startindex":startIndex, "endindex":endIndex], encoding: JSONEncoding.default)
            
        case .saleComplateAuctionVehicleList(let startIndex ,let endIndex):
            return .requestParameters(parameters: ["startindex":startIndex, "endindex":endIndex], encoding: JSONEncoding.default)
            
        case .search(let request):
            return .requestJSONEncodable(request)
            
        case .notifications:
            return .requestParameters(parameters: ["startindex":-1, "endindex":-1], encoding: JSONEncoding.default)
            
        case .auctionVisit(let auctionID):
            return .requestParameters(parameters: ["auctionid":auctionID], encoding: JSONEncoding.default)

        case .resetPassword(let email):
            return .requestParameters(parameters: ["email":email], encoding: JSONEncoding.default)


        default:
            return .requestPlain
        }
        
    }
    
    public var headers: [String : String]? {
        if let key = UserManager.shared.loginKey {
            return ["key": key,"Content-Type":"application/json"]
        } else {
            return ["Content-Type":"application/json"]
        }
    }
}

**Comment by Etnhy** [comment]
> @iballanПохоже, я нашел решение. Вы должны использовать собственную конечную точку, и URL-адрес должен оставаться правильным, не меняясь с '?' to '%3F' Это мой реальный метод, который работает в этой ситуации
> 
> ```
>     let authPlugin = AccessTokenPlugin(token: token)
>     let provider = RxMoyaProvider<Service>(endpointClosure: {target in
>       return Endpoint(
>         url: "\(target.baseURL)\(target.path)",
>         sampleResponseClosure: { .networkResponse(200, target.sampleData) },
>         method: target.method,
>         parameters: target.parameters,
>         parameterEncoding: target.parameterEncoding
>       )
>     }, plugins: [authPlugin])
> ```

2023...
it still works!
