### ISSUE TITLE
MoyaAvailability.swift marks Moya.Error  as unavaliable, but also tries to use Moya.Error in the same file

### ISSUE THREAD

**Issue by aufflick** [Moya/Moya#952]
As of Jan 4 commit, MoyaAvailability.swift marks Moya.Error as unavaliable, but also tries to use Moya.Error in the same file:

```swift
@available(*, unavailable, renamed: "MoyaError", message: "Moya.Error has been renamed to MoyaError in version 8.0.0")
public typealias Error = MoyaError

...
    func didReceiveResponse(result: Result<Moya.Response, Moya.Error>, target: TargetType) { fatalError() }
```

Generates a compiler error.

**Comment by aufflick** [comment]
Ah - it's only a compiler error in Swift 3.1. Swift 3.0 seems to only apply the @unavailable outside the file.

**Comment by scottrhoyt** [comment]
Thanks for bringing that up though! We should put that on our radar for Swift 3.1 release @Moya/contributors.

**Comment by hartbit** [comment]
Since Swift 3.1 is supposed to be backwards compatible with Swift 3.0, I think the Swift dev team will be interested by this: @DougGregor @jckarter

**Comment by BasThomas** [comment]
This is true indeed; Swift 3.1 should be source compatible with 3.0.

**Comment by jckarter** [comment]
This sounds like a bug fix to me, but I'll raise it with the core team.

**Comment by jckarter** [comment]
There was a fix that attempted to emulate the 3.0 behavior and emit warnings in this case:

https://github.com/apple/swift/commit/9489f10ce1feb60e9fb0a32857a273a22420253b

It's recent enough that it may not have made it into 8.3 beta 1. Do you still see the error in 8.3 beta 2, or in a Swift 3.1 snapshot toolchain from swift.org?

**Comment by DougGregor** [comment]
The Swift 3.0 compatibility fix @jckarter referred to was first introduced in Xcode 8.3 beta 2.

**Comment by hartbit** [comment]
@DougGregor This is still happening on Xcode 8.3 Beta 2 and with the latest 3.1 Toolchain (2017-02-07).

**Comment by ened** [comment]
Should this meanwhile be fixed in Moya (and renamed to MoyaError)?

**Comment by scottrhoyt** [comment]
@ened as long as we can verify that doing so still offers the fix-its when trying to use the renamed methods, I think that is reasonable.

**Comment by jckarter** [comment]
The availability fixits should still appear. Let us know if they don't. The only change should have been to tighten up the checking of availability on typealiases.

**Comment by scottrhoyt** [comment]
Thanks everyone. PR inbound.

**Comment by sandeepbol** [comment]
I am trying to convert my Project from Swift 2.3 to Swift 3 in Xcode 8.3 beta 2. What should be done here to fix this issue. If I try to rename Error to MoyaError, Xcode cribs that I file is locked to changes. Still new to Swift and this migration is getting little painful. Any help is appreciated.

Thanks.

**Comment by BasThomas** [comment]
This fix has not been in a release yet, right @scottrhoyt?
