### ISSUE TITLE
How To Handle Self Signed SSL Certificates Over HTTPS

### ISSUE THREAD

**Issue by camcoding** [Moya/Moya#992]
I'm building an IOS app using Swift 3 and Moya 8.0.1.  My app needs to connect via HTTPS to a user's own home automation controller (99% of the time the controller has a self signed certificate).  Moya works great when I'm on my own home network and connecting to my automation controller via http and port 80.  However, if I switch it to HTTPS I receive the following error:

underlying(Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9806, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x61800004bfa0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9806, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9806}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.

**Comment by scottrhoyt** [comment]
I could be wrong, but I believe this is more of an App Transport Security issue. Have you tried searching for information/solutions regarding that?

**Comment by camcoding** [comment]
Yes, according to my Info.plist file I should be bypassing ATS completely:

```
<dict>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
        </dict>
       ....... more here
```

**Comment by scottrhoyt** [comment]
Hmm. Well, I'm not sure I can think of where Moya might be interfering with this. Moya runs network requests through Alamofire which in turn uses `URLSession`. I believe this is a configuration that should be happening at the `URLSession` level, but possibly there is something to do at the Alamofire level. [Here is a link](https://github.com/Alamofire/Alamofire#security) to Alamofire's security section that covers some ATS and common issues with self-signed certificates.

**Comment by pedrovereza** [comment]
@camcoding You can use `ServerTrustPolicyManager` from Alamofire:

```swift
let serverTrustPolicies: [String: ServerTrustPolicy] = [
    "your host exactly": .disableEvaluation
]

let manager = Manager(
    configuration: URLSessionConfiguration.default,
    serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
)

let productProvider = MoyaProvider<YourService>(manager: manager, plugins: [NetworkLoggerPlugin(verbose: true)])
```

The only problem is that `ServerTrustPolicyManager` doesn't take wildcards in the policies, meaning that you would need to specify the host, which is fine when you're testing locally but won't work for your users.

From `ServerTrustPolicyManager` source code:

```swift
    /// Returns the `ServerTrustPolicy` for the given host if applicable.
    ///
    /// By default, this method will return the policy that perfectly matches the given host. Subclasses could override
    /// this method and implement more complex mapping implementations such as wildcards.
    ///
    /// - parameter host: The host to use when searching for a matching policy.
    ///
    /// - returns: The server trust policy for the given host if found.
    open func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        return policies[host]
    }
```

What you can do to disable certificate validation is to subclass `ServerTrustPolicyManager` and return `.disableEvaluation` for all hosts:

```swift
class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
    override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        return .disableEvaluation
    }

    public init() {
        super.init(policies: [:])
    }
}
```

and the usage becomes:

```swift
let manager = Manager(
    configuration: URLSessionConfiguration.default,
    serverTrustPolicyManager: CustomServerTrustPoliceManager()
)

let productProvider = MoyaProvider<YourService>(manager: manager, plugins: [NetworkLoggerPlugin(verbose: true)])
```

Let us know if this solves the problem for you :wink:

**Comment by camcoding** [comment]
@pedrovereza  - No luck... I'm still getting the exact same error message.  

`
provider = RxMoyaProvider<MyCustomProvider>(endpointClosure: endpointClosure, manager: DefaultAlamofireManager.sharedInstance, plugins: [NetworkLoggerPlugin(verbose:true)])

class DefaultAlamofireManager: Alamofire.SessionManager {
    static let sharedInstance: DefaultAlamofireManager = {
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders
        configuration.timeoutIntervalForRequest = 20 // as seconds, you can set your request timeout
        configuration.timeoutIntervalForResource = 20 // as seconds, you can set your resource timeout
        configuration.requestCachePolicy = .useProtocolCachePolicy
        
        return DefaultAlamofireManager(configuration: configuration, serverTrustPolicyManager: CustomServerTrustPoliceManager())
    }()
}

class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
    override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        return .disableEvaluation
    }
    public init() {
        super.init(policies: [:])
    }
}
`

**Comment by pedrovereza** [comment]
@camcoding Oh, right. Forgot to mention you also need this in your Info.plist:

![image](https://cloud.githubusercontent.com/assets/1916041/23478752/100d924a-fea1-11e6-968e-5b0f3c38c984.png)

**Comment by camcoding** [comment]
@pedrovereza - Thanks.  I already had that in my Info.plist but I'm still getting the same error...  If I hit the same https rest service from a browser I get the typical "this is not a trusted SSL certificate" warning message.  Even the error message says coming from Moya states:  "Would you like to connect to the server anyway".  Here's the full error logging message again:

> (Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9806, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x60800005bd50 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9806, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9806}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.

**Comment by camcoding** [comment]
Bump...  Nobody on stackoverflow or alamofire have a solution...  Is there a framework that supports self signed SSL certs?  I need something ASAP

**Comment by pedrovereza** [comment]
@camcoding I created a simple project using Moya to access a website that uses a self signed certificate: https://github.com/pedrovereza/SelfSignedMoya. 
There is also a branch that uses `RxMoyaProvider`: https://github.com/pedrovereza/SelfSignedMoya/tree/rxExample

Both use the `CustomServerTrustPoliceManager` described above, plus the entries in the Info.plist.

Can you confirm this project works for your endpoints as well?

**Comment by camcoding** [comment]
@pedrovereza - you are awesome!  Thank you for the reference project...  I merged parts of your project with mine and it's now working.  The only thing that looked different than any of my previous attempts was your CustomServerTrustPolicyManager class implementation (specifically the override func serverTrustPolicy and having it always return .disableEvaluation).  Thanks again!

**Comment by ETmanwenhan** [comment]
@pedrovereza 
Instantiate Manager, but it's still wrong. How to do?

2017-11-17 17:26:51.968639+0800 yiyue[59453:3754730] CredStore - copyIdentPrefs - Error copying Identity cred. Error=-25300, query={
class = idnt;
labl = "https://app200.yiban1314.com:443/";
"r_Ref" = 1;
}
Moya_Logger: [17/11/2017 17:26:52] Response: Received empty network response for MsgRule("2").
underlying(Alamofire.AFError.responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(400)), Optional(Status Code: 400, Data Length: 238))

```swift
func msgRule() {
        
        // 确保项目已经成功导入了cert.cer证书文件
        let pathToCert = Bundle.main.path(forResource: "server", ofType: "cer")
        let localCertificate = NSData(contentsOfFile: pathToCert!)
        let certificates = [SecCertificateCreateWithData(nil, localCertificate!)!]
        
        let serverTrustPolicy = ServerTrustPolicy.pinCertificates(
            certificates: certificates,
            validateCertificateChain: false,
            validateHost: false
        )
        let serverTrustPolicies = ["app200.yiban1314.com" : serverTrustPolicy]
        let serverTrustPolicyManager = ServerTrustPolicyManager(policies: serverTrustPolicies)
        
        let manager = Manager(
            configuration: URLSessionConfiguration.default,
            serverTrustPolicyManager: serverTrustPolicyManager
        )
        

        let rxProvider = MoyaProvider<UserAPI>(manager: manager,
                                               plugins: [NetworkLoggerPlugin(verbose: true)])
        rxProvider.rx.request(.MsgRule(to_user_id:"2"))
            .debug()
            .mapJSON()
            .subscribe { event in
                
                switch event {
                case let .success(response):
                    debugPrint(response)
                    break
                case let .error(error):
                    print(error)
                    break
                }
        }
```

**Comment by pedrovereza** [comment]
@ETmanwenhan The error message contains status code `400`. This doesn't seem to be a problem with certificates, as the request is being sent and a response is coming back.

I'd suggest you double check the request you're sending to the server.
